variables:
  ARM_PASS: 

trigger:
- none

pool: 
  vmImage: 'windows-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '101-vm-simple-windows'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Pay-As-You-Go(89b51123-0aac-4561-8ebf-df27c242fec1)'
    subscriptionId: '89b51123-0aac-4561-8ebf-df27c242fec1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'myResourceGroup'
    location: 'Australia Southeast'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: '-adminUsername $(adminUsername) -adminPassword $(adminPassword) -vmName $(vmName)'
    deploymentMode: 'Incremental'
