variables:
  ARM_PASS: $(adminPassword)

trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '101-vm-simple-windows'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'az connection nonprod'
    subscriptionId: '09dee83d-9601-47e3-987c-fa3e50df110a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'in-ea-arm-dev-rg'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: '-adminUsername $(adminUsername) -administratorLoginPassword $(ARM_PASS)'
    deploymentMode: 'Incremental'