variables:
  ARM_PASS: $(adminPassword)

trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '101-vm-simple-windows'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

